### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by leonbeau** [issammani/unlimited-medium#23]

**Comment by issammani** [comment]
Hey @leonbeau, I just tested it on a medium page and it works as expected 😄 . Can you please provide more context ?
- What site are you using it on ?
- How are you using it ?
- Ideally, can you share a screen recording ?

**Comment by issammani** [comment]
Closing this as incomplete. Feel free to reopen.

**Comment by muhammedOzbilici24** [comment]
unfortunately not working for both chrome and firefox.
